[project]
name = "04-ml-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bsis09872", email = "bsis09872@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[project.scripts]
04-ml-exercise = "04_ml_exercise:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
